"""create agent runtime tables

Revision ID: 8e2770d42612
Revises:
Create Date: 2026-10-09 15:58:53.291502
"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

revision: str = "8e2770d42612"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "agent_releases",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("agent_id", sa.String(length=128), nullable=False),
        sa.Column("space_id", sa.String(length=128), nullable=False),
        sa.Column("version", sa.String(length=64), nullable=False),
        sa.Column("mode", sa.String(length=32), nullable=False),
        sa.Column("snapshot", sa.JSON(), nullable=False),
        sa.Column("status", sa.String(length=32), nullable=False),
        sa.Column("is_default", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("disabled_at", sa.DateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("agent_id", "version", name="uq_agent_release_version"),
    )
    op.create_index(
        op.f("ix_agent_releases_agent_id"), "agent_releases", ["agent_id"], unique=False
    )
    op.create_index(
        "ix_agent_releases_default",
        "agent_releases",
        ["agent_id", "is_default", "status"],
        unique=False,
    )
    op.create_index(
        op.f("ix_agent_releases_space_id"), "agent_releases", ["space_id"], unique=False
    )
    op.create_table(
        "app_agent_bindings",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("app_id", sa.String(length=128), nullable=False),
        sa.Column("agent_id", sa.String(length=128), nullable=False),
        sa.Column("space_id", sa.String(length=128), nullable=False),
        sa.Column("enabled", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("app_id", "agent_id", name="uq_app_agent_binding"),
    )
    op.create_index(
        op.f("ix_app_agent_bindings_agent_id"),
        "app_agent_bindings",
        ["agent_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_app_agent_bindings_app_id"),
        "app_agent_bindings",
        ["app_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_app_agent_bindings_space_id"),
        "app_agent_bindings",
        ["space_id"],
        unique=False,
    )
    op.create_table(
        "runtime_outbox",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("topic", sa.String(length=128), nullable=False),
        sa.Column("payload", sa.JSON(), nullable=False),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.Column("attempts", sa.Integer(), nullable=False),
        sa.Column("available_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("published_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("last_error", sa.Text(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_runtime_outbox_pending",
        "runtime_outbox",
        ["status", "available_at"],
        unique=False,
    )
    op.create_table(
        "agent_runs",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("trace_id", sa.String(length=36), nullable=False),
        sa.Column("agent_id", sa.String(length=128), nullable=False),
        sa.Column("release_id", sa.String(length=36), nullable=False),
        sa.Column("release_version", sa.String(length=64), nullable=False),
        sa.Column("mode", sa.String(length=32), nullable=False),
        sa.Column("app_id", sa.String(length=128), nullable=False),
        sa.Column("space_id", sa.String(length=128), nullable=False),
        sa.Column("end_user_id", sa.String(length=256), nullable=False),
        sa.Column("conversation_id", sa.String(length=256), nullable=True),
        sa.Column("status", sa.String(length=32), nullable=False),
        sa.Column("input_data", sa.JSON(), nullable=False),
        sa.Column("result_data", sa.JSON(), nullable=True),
        sa.Column("error_code", sa.String(length=64), nullable=True),
        sa.Column("error_message", sa.Text(), nullable=True),
        sa.Column("idempotency_key", sa.String(length=128), nullable=False),
        sa.Column("request_hash", sa.String(length=64), nullable=False),
        sa.Column("cancel_requested", sa.Boolean(), nullable=False),
        sa.Column("attempt", sa.Integer(), nullable=False),
        sa.Column("lease_owner", sa.String(length=128), nullable=True),
        sa.Column("lease_expires_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("finished_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["release_id"],
            ["agent_releases.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("app_id", "idempotency_key", name="uq_run_idempotency"),
    )
    op.create_index(
        op.f("ix_agent_runs_agent_id"), "agent_runs", ["agent_id"], unique=False
    )
    op.create_index(
        op.f("ix_agent_runs_app_id"), "agent_runs", ["app_id"], unique=False
    )
    op.create_index(
        op.f("ix_agent_runs_end_user_id"), "agent_runs", ["end_user_id"], unique=False
    )
    op.create_index(
        "ix_agent_runs_owner",
        "agent_runs",
        ["app_id", "space_id", "end_user_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_agent_runs_release_id"), "agent_runs", ["release_id"], unique=False
    )
    op.create_index(
        op.f("ix_agent_runs_space_id"), "agent_runs", ["space_id"], unique=False
    )
    op.create_index(
        "ix_agent_runs_status_updated",
        "agent_runs",
        ["status", "updated_at"],
        unique=False,
    )
    op.create_table(
        "run_approvals",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("run_id", sa.String(length=36), nullable=False),
        sa.Column("operation_id", sa.String(length=128), nullable=False),
        sa.Column("parameter_hash", sa.String(length=64), nullable=False),
        sa.Column("policy", sa.JSON(), nullable=False),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.Column("decided_by", sa.String(length=256), nullable=True),
        sa.Column("decision_reason", sa.Text(), nullable=True),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("decided_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["run_id"],
            ["agent_runs.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_run_approvals_run_id"), "run_approvals", ["run_id"], unique=False
    )
    op.create_table(
        "run_events",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("run_id", sa.String(length=36), nullable=False),
        sa.Column("event_type", sa.String(length=64), nullable=False),
        sa.Column("step_id", sa.String(length=128), nullable=True),
        sa.Column("trace_id", sa.String(length=36), nullable=False),
        sa.Column("data", sa.JSON(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["run_id"],
            ["agent_runs.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_run_events_run_id"), "run_events", ["run_id"], unique=False
    )
    op.create_index(
        "ix_run_events_run_sequence", "run_events", ["run_id", "id"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_run_events_run_sequence", table_name="run_events")
    op.drop_index(op.f("ix_run_events_run_id"), table_name="run_events")
    op.drop_table("run_events")
    op.drop_index(op.f("ix_run_approvals_run_id"), table_name="run_approvals")
    op.drop_table("run_approvals")
    op.drop_index("ix_agent_runs_status_updated", table_name="agent_runs")
    op.drop_index(op.f("ix_agent_runs_space_id"), table_name="agent_runs")
    op.drop_index(op.f("ix_agent_runs_release_id"), table_name="agent_runs")
    op.drop_index("ix_agent_runs_owner", table_name="agent_runs")
    op.drop_index(op.f("ix_agent_runs_end_user_id"), table_name="agent_runs")
    op.drop_index(op.f("ix_agent_runs_app_id"), table_name="agent_runs")
    op.drop_index(op.f("ix_agent_runs_agent_id"), table_name="agent_runs")
    op.drop_table("agent_runs")
    op.drop_index("ix_runtime_outbox_pending", table_name="runtime_outbox")
    op.drop_table("runtime_outbox")
    op.drop_index(
        op.f("ix_app_agent_bindings_space_id"), table_name="app_agent_bindings"
    )
    op.drop_index(op.f("ix_app_agent_bindings_app_id"), table_name="app_agent_bindings")
    op.drop_index(
        op.f("ix_app_agent_bindings_agent_id"), table_name="app_agent_bindings"
    )
    op.drop_table("app_agent_bindings")
    op.drop_index(op.f("ix_agent_releases_space_id"), table_name="agent_releases")
    op.drop_index("ix_agent_releases_default", table_name="agent_releases")
    op.drop_index(op.f("ix_agent_releases_agent_id"), table_name="agent_releases")
    op.drop_table("agent_releases")
    # ### end Alembic commands ###
