"""add governed tool calls and material drafts

Revision ID: c940d359a82b
Revises: 8e2770d42612
Create Date: 2026-10-09 16:06:48.133868
"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

revision: str = "c940d359a82b"
down_revision: Union[str, None] = "8e2770d42612"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "commerce_material_drafts",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("space_id", sa.String(length=128), nullable=False),
        sa.Column("end_user_id", sa.String(length=256), nullable=False),
        sa.Column("product_id", sa.String(length=128), nullable=False),
        sa.Column("logical_operation_id", sa.String(length=128), nullable=False),
        sa.Column("content", sa.JSON(), nullable=False),
        sa.Column("status", sa.String(length=32), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "space_id", "logical_operation_id", name="uq_material_draft_operation"
        ),
    )
    op.create_index(
        op.f("ix_commerce_material_drafts_end_user_id"),
        "commerce_material_drafts",
        ["end_user_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_commerce_material_drafts_product_id"),
        "commerce_material_drafts",
        ["product_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_commerce_material_drafts_space_id"),
        "commerce_material_drafts",
        ["space_id"],
        unique=False,
    )
    op.create_table(
        "run_tool_calls",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("run_id", sa.String(length=36), nullable=False),
        sa.Column("step_id", sa.String(length=128), nullable=False),
        sa.Column("tool_name", sa.String(length=128), nullable=False),
        sa.Column("logical_operation_id", sa.String(length=128), nullable=False),
        sa.Column("argument_hash", sa.String(length=64), nullable=False),
        sa.Column("arguments", sa.JSON(), nullable=False),
        sa.Column("status", sa.String(length=32), nullable=False),
        sa.Column("result", sa.JSON(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["run_id"],
            ["agent_runs.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "run_id", "logical_operation_id", name="uq_tool_call_logical_operation"
        ),
    )
    op.create_index(
        op.f("ix_run_tool_calls_run_id"), "run_tool_calls", ["run_id"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_run_tool_calls_run_id"), table_name="run_tool_calls")
    op.drop_table("run_tool_calls")
    op.drop_index(
        op.f("ix_commerce_material_drafts_space_id"),
        table_name="commerce_material_drafts",
    )
    op.drop_index(
        op.f("ix_commerce_material_drafts_product_id"),
        table_name="commerce_material_drafts",
    )
    op.drop_index(
        op.f("ix_commerce_material_drafts_end_user_id"),
        table_name="commerce_material_drafts",
    )
    op.drop_table("commerce_material_drafts")
    # ### end Alembic commands ###
