"""init tables

Revision ID: 76f8768467ee
Revises:
Create Date: 2026-01-19 15:06:05.861114

"""

from typing import Sequence, Union

import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import mysql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "76f8768467ee"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """升级数据库架构"""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("async_chat_result_execute_id_uindex", table_name="async_chat_result")
    op.drop_table("async_chat_result")
    op.drop_index("udx_action_tool_id", table_name="http_action_tool")
    op.drop_table("http_action_tool")
    op.alter_column(
        "app",
        "id",
        existing_type=mysql.BIGINT(display_width=20),
        type_=sa.Integer(),
        existing_nullable=False,
    )
    op.alter_column(
        "app",
        "name",
        existing_type=mysql.VARCHAR(length=30),
        type_=sqlmodel.sql.sqltypes.AutoString(),
        nullable=False,
    )
    op.alter_column(
        "app",
        "alias_id",
        existing_type=mysql.VARCHAR(length=64),
        type_=sqlmodel.sql.sqltypes.AutoString(),
        nullable=False,
        comment=None,
        existing_comment="应用标识",
    )
    op.alter_column(
        "app",
        "api_key",
        existing_type=mysql.VARCHAR(length=50),
        type_=sqlmodel.sql.sqltypes.AutoString(),
        existing_nullable=False,
    )
    op.alter_column(
        "app",
        "api_secret",
        existing_type=mysql.VARCHAR(length=50),
        type_=sqlmodel.sql.sqltypes.AutoString(),
        existing_nullable=False,
    )
    op.alter_column(
        "app", "description", existing_type=mysql.VARCHAR(length=255), nullable=False
    )
    op.alter_column(
        "app",
        "is_tenant",
        existing_type=mysql.TINYINT(display_width=4),
        server_default=None,
        type_=sa.Integer(),
        nullable=False,
        comment=None,
        existing_comment="是否为租户app\n0: 否\n1: 是",
    )
    op.alter_column(
        "app",
        "source",
        existing_type=mysql.TINYINT(display_width=4),
        server_default=None,
        type_=sa.Integer(),
        nullable=False,
        comment=None,
        existing_comment="租户归属。\n1: 星辰平台\n2: 开放平台\n4: AIUI",
    )
    op.alter_column(
        "app",
        "actual_source",
        existing_type=mysql.TINYINT(display_width=4),
        server_default=None,
        type_=sa.Integer(),
        nullable=False,
        comment=None,
        existing_comment="应用实际归属",
    )
    op.alter_column(
        "app",
        "plat_release_auth",
        existing_type=mysql.TINYINT(display_width=4),
        server_default=None,
        type_=sa.Integer(),
        nullable=False,
        comment=None,
        existing_comment="针对租户账户，提供平台授权权限。值为source或值",
    )
    op.alter_column(
        "app",
        "status",
        existing_type=mysql.TINYINT(display_width=4),
        server_default=None,
        type_=sa.Integer(),
        nullable=False,
        comment=None,
        existing_comment="应用状态\n0: 禁用\n1: 启用",
    )
    op.alter_column(
        "app",
        "audit_policy",
        existing_type=mysql.TINYINT(display_width=4),
        server_default=None,
        type_=sa.Integer(),
        nullable=False,
    )
    op.alter_column(
        "app",
        "create_by",
        existing_type=mysql.BIGINT(display_width=20),
        type_=sa.Integer(),
        nullable=False,
        comment=None,
        existing_comment="创建人",
    )
    op.alter_column(
        "app",
        "update_by",
        existing_type=mysql.BIGINT(display_width=20),
        type_=sa.Integer(),
        nullable=False,
        comment=None,
        existing_comment="更新人",
    )
    op.alter_column(
        "app",
        "create_at",
        existing_type=mysql.DATETIME(),
        nullable=False,
        comment=None,
        existing_comment="创建时间",
    )
    op.alter_column(
        "app",
        "update_at",
        existing_type=mysql.DATETIME(),
        nullable=False,
        comment=None,
        existing_comment="更新时间",
    )
    op.drop_index("alias_id", table_name="app")
    op.drop_index("idx_appid", table_name="app")
    op.drop_table_comment("app", existing_comment="app 信息", schema=None)
    op.alter_column(
        "app_source",
        "id",
        existing_type=mysql.BIGINT(display_width=20),
        type_=sa.Integer(),
        existing_nullable=False,
    )
    op.alter_column(
        "app_source",
        "source",
        existing_type=mysql.TINYINT(display_width=4),
        type_=sa.Integer(),
        comment=None,
        existing_comment="租户源，枚举值：\n1: 星辰\n2: 开放平台\n4: AIUI\n8: 飞云",
        existing_nullable=False,
    )
    op.alter_column(
        "app_source",
        "source_id",
        existing_type=mysql.VARCHAR(length=32),
        type_=sqlmodel.sql.sqltypes.AutoString(),
        comment=None,
        existing_comment="租户应用ID",
        existing_nullable=False,
    )
    op.alter_column(
        "app_source",
        "description",
        existing_type=mysql.VARCHAR(length=16),
        type_=sqlmodel.sql.sqltypes.AutoString(),
        existing_nullable=False,
    )
    op.create_unique_constraint(None, "app_source", ["id"])
    op.alter_column(
        "flow",
        "id",
        existing_type=mysql.BIGINT(display_width=20),
        type_=sa.Integer(),
        existing_nullable=False,
    )
    op.alter_column(
        "flow",
        "group_id",
        existing_type=mysql.BIGINT(display_width=20),
        server_default=None,
        type_=sa.Integer(),
        nullable=False,
    )
    op.alter_column(
        "flow",
        "name",
        existing_type=mysql.VARCHAR(length=128),
        type_=sqlmodel.sql.sqltypes.AutoString(),
        comment=None,
        existing_comment="协议名称",
        existing_nullable=False,
    )
    op.alter_column(
        "flow",
        "data",
        existing_type=mysql.MEDIUMTEXT(),
        type_=sa.JSON(),
        comment=None,
        existing_comment="编排标准协议",
        existing_nullable=True,
    )
    op.alter_column(
        "flow",
        "release_data",
        existing_type=mysql.MEDIUMTEXT(),
        type_=sa.JSON(),
        comment=None,
        existing_comment="发布后的数据",
        existing_nullable=True,
    )
    op.alter_column(
        "flow",
        "description",
        existing_type=mysql.VARCHAR(length=1024),
        type_=sqlmodel.sql.sqltypes.AutoString(),
        nullable=False,
    )
    op.alter_column(
        "flow",
        "version",
        existing_type=mysql.VARCHAR(length=128),
        server_default=None,
        type_=sqlmodel.sql.sqltypes.AutoString(),
        nullable=False,
        comment=None,
        existing_comment="协议版本",
    )
    op.alter_column(
        "flow",
        "release_status",
        existing_type=mysql.TINYINT(display_width=4),
        type_=sa.Integer(),
        nullable=False,
        comment=None,
        existing_comment="发布状态或值",
    )
    op.alter_column(
        "flow",
        "app_id",
        existing_type=mysql.VARCHAR(length=255),
        nullable=False,
        comment=None,
        existing_comment="app_id",
    )
    op.alter_column(
        "flow",
        "source",
        existing_type=mysql.TINYINT(display_width=4),
        server_default=None,
        type_=sa.Integer(),
        nullable=False,
        comment=None,
        existing_comment="来源",
    )
    op.alter_column(
        "flow",
        "create_at",
        existing_type=mysql.DATETIME(),
        server_default=None,
        nullable=False,
    )
    op.alter_column(
        "flow",
        "tag",
        existing_type=mysql.INTEGER(display_width=11),
        nullable=False,
        comment=None,
        existing_comment="标记工作流标签 0：无标签；1：对照组",
    )
    op.alter_column(
        "flow",
        "update_at",
        existing_type=mysql.DATETIME(),
        server_default=None,
        nullable=False,
    )
    op.drop_index("idx_flow_name", table_name="flow")
    op.drop_index("uniq_group_id_version", table_name="flow")
    op.create_index(op.f("ix_flow_description"), "flow", ["description"], unique=False)
    op.create_index(op.f("ix_flow_group_id"), "flow", ["group_id"], unique=True)
    op.create_index(op.f("ix_flow_name"), "flow", ["name"], unique=False)
    op.create_index(op.f("ix_flow_version"), "flow", ["version"], unique=False)
    op.create_unique_constraint(None, "flow", ["id"])
    op.drop_column("flow", "update_by")
    op.drop_column("flow", "status")
    op.drop_column("flow", "create_by")
    op.alter_column(
        "license",
        "id",
        existing_type=mysql.BIGINT(display_width=20),
        type_=sa.Integer(),
        existing_nullable=False,
    )
    op.alter_column(
        "license",
        "app_id",
        existing_type=mysql.BIGINT(display_width=20),
        type_=sa.Integer(),
        existing_nullable=False,
    )
    op.alter_column(
        "license",
        "group_id",
        existing_type=mysql.BIGINT(display_width=20),
        type_=sa.Integer(),
        existing_nullable=False,
    )
    op.alter_column(
        "license",
        "status",
        existing_type=mysql.TINYINT(display_width=4),
        server_default=None,
        type_=sa.Integer(),
        comment=None,
        existing_comment="授权状态\n0: 禁用\n1: 启用",
        existing_nullable=False,
    )
    op.drop_index("idx_app_id_group_id", table_name="license")
    op.drop_index("lic_uk_appid_gid", table_name="license")
    op.create_index(op.f("ix_license_status"), "license", ["status"], unique=False)
    op.create_unique_constraint(None, "license", ["id"])
    op.alter_column(
        "workflow_node_history",
        "uid",
        existing_type=mysql.VARCHAR(length=255),
        nullable=False,
    )
    op.alter_column(
        "workflow_node_history",
        "raw_question",
        existing_type=mysql.MEDIUMTEXT(),
        type_=sqlmodel.sql.sqltypes.AutoString(),
        existing_nullable=True,
    )
    op.alter_column(
        "workflow_node_history",
        "raw_answer",
        existing_type=mysql.MEDIUMTEXT(),
        type_=sqlmodel.sql.sqltypes.AutoString(),
        existing_nullable=True,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """降级数据库架构"""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "workflow_node_history",
        "raw_answer",
        existing_type=sqlmodel.sql.sqltypes.AutoString(),
        type_=mysql.MEDIUMTEXT(),
        existing_nullable=True,
    )
    op.alter_column(
        "workflow_node_history",
        "raw_question",
        existing_type=sqlmodel.sql.sqltypes.AutoString(),
        type_=mysql.MEDIUMTEXT(),
        existing_nullable=True,
    )
    op.alter_column(
        "workflow_node_history",
        "uid",
        existing_type=mysql.VARCHAR(length=255),
        nullable=True,
    )
    op.drop_constraint(None, "license", type_="unique")
    op.drop_index(op.f("ix_license_status"), table_name="license")
    op.create_index("lic_uk_appid_gid", "license", ["app_id", "group_id"], unique=True)
    op.create_index(
        "idx_app_id_group_id", "license", ["app_id", "group_id"], unique=False
    )
    op.alter_column(
        "license",
        "status",
        existing_type=sa.Integer(),
        server_default=sa.text("'1'"),
        type_=mysql.TINYINT(display_width=4),
        comment="授权状态\n0: 禁用\n1: 启用",
        existing_nullable=False,
    )
    op.alter_column(
        "license",
        "group_id",
        existing_type=sa.Integer(),
        type_=mysql.BIGINT(display_width=20),
        existing_nullable=False,
    )
    op.alter_column(
        "license",
        "app_id",
        existing_type=sa.Integer(),
        type_=mysql.BIGINT(display_width=20),
        existing_nullable=False,
    )
    op.alter_column(
        "license",
        "id",
        existing_type=sa.Integer(),
        type_=mysql.BIGINT(display_width=20),
        existing_nullable=False,
    )
    op.add_column(
        "flow",
        sa.Column(
            "create_by",
            mysql.BIGINT(display_width=20),
            server_default=sa.text("'0'"),
            autoincrement=False,
            nullable=False,
            comment="创建人",
        ),
    )
    op.add_column(
        "flow",
        sa.Column(
            "status",
            mysql.TINYINT(display_width=1),
            autoincrement=False,
            nullable=False,
            comment="flow的状态，0是草稿，1是发布",
        ),
    )
    op.add_column(
        "flow",
        sa.Column(
            "update_by",
            mysql.BIGINT(display_width=20),
            autoincrement=False,
            nullable=True,
            comment="更新人",
        ),
    )
    op.drop_constraint(None, "flow", type_="unique")
    op.drop_index(op.f("ix_flow_version"), table_name="flow")
    op.drop_index(op.f("ix_flow_name"), table_name="flow")
    op.drop_index(op.f("ix_flow_group_id"), table_name="flow")
    op.drop_index(op.f("ix_flow_description"), table_name="flow")
    op.create_index(
        "uniq_group_id_version", "flow", ["group_id", "version"], unique=True
    )
    op.create_index("idx_flow_name", "flow", ["name"], unique=False)
    op.alter_column(
        "flow",
        "update_at",
        existing_type=mysql.DATETIME(),
        server_default=sa.text("CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP"),
        nullable=True,
    )
    op.alter_column(
        "flow",
        "tag",
        existing_type=mysql.INTEGER(display_width=11),
        nullable=True,
        comment="标记工作流标签 0：无标签；1：对照组",
    )
    op.alter_column(
        "flow",
        "create_at",
        existing_type=mysql.DATETIME(),
        server_default=sa.text("CURRENT_TIMESTAMP"),
        nullable=True,
    )
    op.alter_column(
        "flow",
        "source",
        existing_type=sa.Integer(),
        server_default=sa.text("'0'"),
        type_=mysql.TINYINT(display_width=4),
        nullable=True,
        comment="来源",
    )
    op.alter_column(
        "flow",
        "app_id",
        existing_type=mysql.VARCHAR(length=255),
        nullable=True,
        comment="app_id",
    )
    op.alter_column(
        "flow",
        "release_status",
        existing_type=sa.Integer(),
        type_=mysql.TINYINT(display_width=4),
        nullable=True,
        comment="发布状态或值",
    )
    op.alter_column(
        "flow",
        "version",
        existing_type=sqlmodel.sql.sqltypes.AutoString(),
        server_default=sa.text("''"),
        type_=mysql.VARCHAR(length=128),
        nullable=True,
        comment="协议版本",
    )
    op.alter_column(
        "flow",
        "description",
        existing_type=sqlmodel.sql.sqltypes.AutoString(),
        type_=mysql.VARCHAR(length=1024),
        nullable=True,
    )
    op.alter_column(
        "flow",
        "release_data",
        existing_type=sa.JSON(),
        type_=mysql.MEDIUMTEXT(),
        comment="发布后的数据",
        existing_nullable=True,
    )
    op.alter_column(
        "flow",
        "data",
        existing_type=sa.JSON(),
        type_=mysql.MEDIUMTEXT(),
        comment="编排标准协议",
        existing_nullable=True,
    )
    op.alter_column(
        "flow",
        "name",
        existing_type=sqlmodel.sql.sqltypes.AutoString(),
        type_=mysql.VARCHAR(length=128),
        comment="协议名称",
        existing_nullable=False,
    )
    op.alter_column(
        "flow",
        "group_id",
        existing_type=sa.Integer(),
        server_default=sa.text("'0'"),
        type_=mysql.BIGINT(display_width=20),
        nullable=True,
    )
    op.alter_column(
        "flow",
        "id",
        existing_type=sa.Integer(),
        type_=mysql.BIGINT(display_width=20),
        existing_nullable=False,
    )
    op.drop_constraint(None, "app_source", type_="unique")
    op.alter_column(
        "app_source",
        "description",
        existing_type=sqlmodel.sql.sqltypes.AutoString(),
        type_=mysql.VARCHAR(length=16),
        existing_nullable=False,
    )
    op.alter_column(
        "app_source",
        "source_id",
        existing_type=sqlmodel.sql.sqltypes.AutoString(),
        type_=mysql.VARCHAR(length=32),
        comment="租户应用ID",
        existing_nullable=False,
    )
    op.alter_column(
        "app_source",
        "source",
        existing_type=sa.Integer(),
        type_=mysql.TINYINT(display_width=4),
        comment="租户源，枚举值：\n1: 星辰\n2: 开放平台\n4: AIUI\n8: 飞云",
        existing_nullable=False,
    )
    op.alter_column(
        "app_source",
        "id",
        existing_type=sa.Integer(),
        type_=mysql.BIGINT(display_width=20),
        existing_nullable=False,
    )
    op.create_table_comment("app", "app 信息", existing_comment=None, schema=None)
    op.create_index("idx_appid", "app", ["alias_id"], unique=False)
    op.create_index("alias_id", "app", ["alias_id"], unique=True)
    op.alter_column(
        "app",
        "update_at",
        existing_type=mysql.DATETIME(),
        nullable=True,
        comment="更新时间",
    )
    op.alter_column(
        "app",
        "create_at",
        existing_type=mysql.DATETIME(),
        nullable=True,
        comment="创建时间",
    )
    op.alter_column(
        "app",
        "update_by",
        existing_type=sa.Integer(),
        type_=mysql.BIGINT(display_width=20),
        nullable=True,
        comment="更新人",
    )
    op.alter_column(
        "app",
        "create_by",
        existing_type=sa.Integer(),
        type_=mysql.BIGINT(display_width=20),
        nullable=True,
        comment="创建人",
    )
    op.alter_column(
        "app",
        "audit_policy",
        existing_type=sa.Integer(),
        server_default=sa.text("'0'"),
        type_=mysql.TINYINT(display_width=4),
        nullable=True,
    )
    op.alter_column(
        "app",
        "status",
        existing_type=sa.Integer(),
        server_default=sa.text("'1'"),
        type_=mysql.TINYINT(display_width=4),
        nullable=True,
        comment="应用状态\n0: 禁用\n1: 启用",
    )
    op.alter_column(
        "app",
        "plat_release_auth",
        existing_type=sa.Integer(),
        server_default=sa.text("'0'"),
        type_=mysql.TINYINT(display_width=4),
        nullable=True,
        comment="针对租户账户，提供平台授权权限。值为source或值",
    )
    op.alter_column(
        "app",
        "actual_source",
        existing_type=sa.Integer(),
        server_default=sa.text("'0'"),
        type_=mysql.TINYINT(display_width=4),
        nullable=True,
        comment="应用实际归属",
    )
    op.alter_column(
        "app",
        "source",
        existing_type=sa.Integer(),
        server_default=sa.text("'0'"),
        type_=mysql.TINYINT(display_width=4),
        nullable=True,
        comment="租户归属。\n1: 星辰平台\n2: 开放平台\n4: AIUI",
    )
    op.alter_column(
        "app",
        "is_tenant",
        existing_type=sa.Integer(),
        server_default=sa.text("'0'"),
        type_=mysql.TINYINT(display_width=4),
        nullable=True,
        comment="是否为租户app\n0: 否\n1: 是",
    )
    op.alter_column(
        "app", "description", existing_type=mysql.VARCHAR(length=255), nullable=True
    )
    op.alter_column(
        "app",
        "api_secret",
        existing_type=sqlmodel.sql.sqltypes.AutoString(),
        type_=mysql.VARCHAR(length=50),
        existing_nullable=False,
    )
    op.alter_column(
        "app",
        "api_key",
        existing_type=sqlmodel.sql.sqltypes.AutoString(),
        type_=mysql.VARCHAR(length=50),
        existing_nullable=False,
    )
    op.alter_column(
        "app",
        "alias_id",
        existing_type=sqlmodel.sql.sqltypes.AutoString(),
        type_=mysql.VARCHAR(length=64),
        nullable=True,
        comment="应用标识",
    )
    op.alter_column(
        "app",
        "name",
        existing_type=sqlmodel.sql.sqltypes.AutoString(),
        type_=mysql.VARCHAR(length=30),
        nullable=True,
    )
    op.alter_column(
        "app",
        "id",
        existing_type=sa.Integer(),
        type_=mysql.BIGINT(display_width=20),
        existing_nullable=False,
    )
    op.create_table(
        "http_action_tool",
        sa.Column(
            "id", mysql.BIGINT(display_width=20), autoincrement=False, nullable=False
        ),
        sa.Column("tool_id", mysql.VARCHAR(length=32), nullable=True, comment="工具ID"),
        sa.Column("name", mysql.VARCHAR(length=128), nullable=True),
        sa.Column(
            "open_api_schema",
            mysql.MEDIUMTEXT(),
            nullable=True,
            comment="open api schema，json格式",
        ),
        sa.Column(
            "plugin_schema",
            mysql.VARCHAR(length=128),
            server_default=sa.text("''"),
            nullable=True,
            comment="大模型插件协议",
        ),
        sa.Column(
            "create_at",
            mysql.DATETIME(),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            nullable=True,
        ),
        sa.Column(
            "update_at",
            mysql.DATETIME(),
            server_default=sa.text("CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP"),
            nullable=True,
        ),
        sa.PrimaryKeyConstraint("id"),
        mysql_default_charset="utf8",
        mysql_engine="InnoDB",
    )
    op.create_index("udx_action_tool_id", "http_action_tool", ["tool_id"], unique=True)
    op.create_table(
        "async_chat_result",
        sa.Column(
            "id", mysql.BIGINT(display_width=20), autoincrement=True, nullable=False
        ),
        sa.Column("execute_id", mysql.VARCHAR(length=255), nullable=False),
        sa.Column("task_id", mysql.VARCHAR(length=255), nullable=False),
        sa.Column(
            "app_id",
            mysql.BIGINT(display_width=20),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column(
            "flow_id",
            mysql.BIGINT(display_width=20),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column("sid", mysql.VARCHAR(length=255), nullable=False),
        sa.Column("uid", mysql.VARCHAR(length=255), nullable=False),
        sa.Column("status", mysql.VARCHAR(length=255), nullable=False),
        sa.Column(
            "err_code",
            mysql.INTEGER(display_width=11),
            server_default=sa.text("'0'"),
            autoincrement=False,
            nullable=False,
            comment="错误码，0表示成功",
        ),
        sa.Column("err_message", mysql.VARCHAR(length=2048), nullable=True),
        sa.Column("input_url", mysql.VARCHAR(length=2048), nullable=True),
        sa.Column("output_url", mysql.VARCHAR(length=2048), nullable=True),
        sa.Column(
            "create_at",
            mysql.DATETIME(),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            nullable=False,
        ),
        sa.Column(
            "update_at",
            mysql.DATETIME(),
            server_default=sa.text("CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP"),
            nullable=False,
        ),
        sa.Column(
            "version",
            mysql.VARCHAR(length=128),
            server_default=sa.text("''"),
            nullable=True,
        ),
        sa.PrimaryKeyConstraint("id"),
        comment="异步API执行结果",
        mysql_comment="异步API执行结果",
        mysql_default_charset="utf8",
        mysql_engine="InnoDB",
    )
    op.create_index(
        "async_chat_result_execute_id_uindex",
        "async_chat_result",
        ["execute_id"],
        unique=True,
    )
    # ### end Alembic commands ###
