# Common general configuration
# Blacklist configuration
SEGMENT_BLACK_LIST_KEY = "SEGMENT_BLACK_LIST"
IP_BLACK_LIST_KEY = "IP_BLACK_LIST"
DOMAIN_BLACK_LIST_KEY = "DOMAIN_BLACK_LIST"
# Distinguish between official and third-party tools
OFFICIAL_TOOL_KEY = "OFFICIAL_TOOL"
THIRD_TOOL_KEY = "THIRD_TOOL"
# Official default app ID
DEFAULT_APPID_KEY = "DEFAULT_APPID"
# ID generation
DATACENTER_ID_KEY = "DATACENTER_ID"
WORKER_ID_KEY = "WORKER_ID"

HTTP_AUTH_QU_APP_ID_KEY = "HTTP_AUTH_QU_APP_ID"
HTTP_AUTH_QU_APP_KEY_KEY = "HTTP_AUTH_QU_APP_KEY"
HTTP_AUTH_AWAU_APP_ID_KEY = "HTTP_AUTH_AWAU_APP_ID"
HTTP_AUTH_AWAU_API_KEY_KEY = "HTTP_AUTH_AWAU_API_KEY"
HTTP_AUTH_AWAU_API_SECRET_KEY = "HTTP_AUTH_AWAU_API_SECRET"

# OAuth2 out-bound client credentials configuration
OAUTH2_CLIENT_ID_KEY = "OAUTH2_CLIENT_ID"
OAUTH2_CLIENT_SECRET_KEY = "OAUTH2_CLIENT_SECRET"
OAUTH2_AUDIENCE_KEY = "OAUTH2_AUDIENCE"
OAUTH2_SCOPE_KEY = "OAUTH2_SCOPE"
OAUTH2_TOKEN_URL_KEY = "OAUTH2_TOKEN_URL"

# Optional env-key indirection for per-tool secret resolution
OAUTH2_CLIENT_ID_ENV_KEY = "OAUTH2_CLIENT_ID_ENV"
OAUTH2_CLIENT_SECRET_ENV_KEY = "OAUTH2_CLIENT_SECRET_ENV"
OAUTH2_AUDIENCE_ENV_KEY = "OAUTH2_AUDIENCE_ENV"
OAUTH2_SCOPE_ENV_KEY = "OAUTH2_SCOPE_ENV"
OAUTH2_TOKEN_URL_ENV_KEY = "OAUTH2_TOKEN_URL_ENV"

# JWT in-bound validation switches
JWT_AUTH_ENABLE_KEY = "JWT_AUTH_ENABLE"
JWT_AUTH_EXCLUDE_PATHS_KEY = "JWT_AUTH_EXCLUDE_PATHS"
JWT_AUTH_HEADER_KEY = "JWT_AUTH_HEADER"
JWT_AUDIENCE_KEY = "JWT_AUDIENCE"
JWT_ISSUER_KEY = "JWT_ISSUER"
JWT_ALGORITHMS_KEY = "JWT_ALGORITHMS"
JWT_JWKS_URL_KEY = "JWT_JWKS_URL"
JWT_SHARED_SECRET_KEY = "JWT_SHARED_SECRET"
