CREATE TABLE IF NOT EXISTS `workflow_automation_task` (
  `id` bigint NOT NULL AUTO_INCREMENT COMMENT 'Primary key',
  `task_name` varchar(128) NOT NULL COMMENT 'Automation task name',
  `flow_id` varchar(128) NOT NULL COMMENT 'Workflow flow id',
  `workflow_name` varchar(255) DEFAULT NULL COMMENT 'Workflow name snapshot',
  `version` varchar(128) DEFAULT NULL COMMENT 'Workflow release version',
  `space_id` bigint DEFAULT NULL COMMENT 'Space id',
  `uid` varchar(64) NOT NULL COMMENT 'Creator uid',
  `cron_expression` varchar(128) NOT NULL COMMENT 'Spring cron expression',
  `schedule_type` varchar(32) DEFAULT 'CUSTOM' COMMENT 'Schedule preset type',
  `timezone` varchar(64) NOT NULL DEFAULT 'Asia/Shanghai' COMMENT 'Schedule timezone',
  `input_params` longtext COMMENT 'Workflow input parameters JSON',
  `enabled` tinyint(1) NOT NULL DEFAULT 1 COMMENT 'Whether enabled',
  `deleted` tinyint(1) NOT NULL DEFAULT 0 COMMENT 'Logical delete flag',
  `next_fire_time` datetime DEFAULT NULL COMMENT 'Next fire time',
  `last_run_time` datetime DEFAULT NULL COMMENT 'Last run time',
  `last_run_status` varchar(32) DEFAULT NULL COMMENT 'Last run status',
  `last_run_message` varchar(512) DEFAULT NULL COMMENT 'Last run message',
  `create_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT 'Create time',
  `update_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT 'Update time',
  PRIMARY KEY (`id`),
  KEY `idx_workflow_automation_task_scope` (`space_id`, `uid`, `deleted`, `enabled`),
  KEY `idx_workflow_automation_task_fire` (`enabled`, `deleted`, `next_fire_time`),
  KEY `idx_workflow_automation_task_flow` (`flow_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='Workflow automation scheduled task';

CREATE TABLE IF NOT EXISTS `workflow_automation_run` (
  `id` bigint NOT NULL AUTO_INCREMENT COMMENT 'Primary key',
  `task_id` bigint NOT NULL COMMENT 'Automation task id',
  `flow_id` varchar(128) NOT NULL COMMENT 'Workflow flow id',
  `space_id` bigint DEFAULT NULL COMMENT 'Space id',
  `uid` varchar(64) NOT NULL COMMENT 'Run owner uid',
  `trigger_type` varchar(32) NOT NULL COMMENT 'SCHEDULE or MANUAL',
  `scheduled_fire_time` datetime DEFAULT NULL COMMENT 'Scheduled fire time',
  `start_time` datetime DEFAULT NULL COMMENT 'Start time',
  `end_time` datetime DEFAULT NULL COMMENT 'End time',
  `status` varchar(32) NOT NULL COMMENT 'SUCCESS/FAILED/SKIPPED/RUNNING',
  `request_params` longtext COMMENT 'Request params snapshot',
  `response_summary` longtext COMMENT 'Response summary',
  `error_message` longtext COMMENT 'Error message',
  `duration_ms` bigint DEFAULT NULL COMMENT 'Execution duration in milliseconds',
  `create_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT 'Create time',
  PRIMARY KEY (`id`),
  KEY `idx_workflow_automation_run_task` (`task_id`, `create_time`),
  KEY `idx_workflow_automation_run_scope` (`space_id`, `uid`, `create_time`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='Workflow automation run record';
